import { StyleSheet, Platform } from 'react-native';

import {
    homeDashboardColors,
    homeDashboardRadii,
    homeDashboardShadows,
    homeDashboardSpacing,
    homeDashboardTypography,
} from '../../home/components/homeDashboardTokens';

export const profileStyles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: homeDashboardColors.paper,
    },
    navBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: homeDashboardSpacing.lg,
        paddingVertical: homeDashboardSpacing.md,
        zIndex: 1,
    },
    navButton: {
        alignItems: 'center',
        borderRadius: homeDashboardRadii.pill,
        justifyContent: 'center',
        minHeight: 44,
        minWidth: 44,
    },
    navTitle: {
        flex: 1,
        fontSize: 17,
        fontWeight: '600',
        lineHeight: 22,
        textAlign: 'center',
    },
    navRightSlot: {
        alignItems: 'flex-end',
        justifyContent: 'center',
        minWidth: 64,
    },
    headerSaveButton: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.ink,
        borderRadius: homeDashboardRadii.pill,
        justifyContent: 'center',
        minHeight: 44,
        minWidth: 64,
        paddingHorizontal: homeDashboardSpacing.md,
    },
    headerSaveButtonText: {
        color: homeDashboardColors.paper,
        fontSize: homeDashboardTypography.bodyStrong,
        fontWeight: '900',
        lineHeight: 18,
    },
    container: {
        flex: 1,
        paddingHorizontal: homeDashboardSpacing.lg,
        zIndex: 1,
    },
    statusRail: {
        alignItems: 'center',
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: homeDashboardSpacing.xs,
        marginTop: homeDashboardSpacing.xs,
    },
    statusRailText: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.caption,
        fontWeight: '800',
        lineHeight: 16,
        textTransform: 'uppercase',
    },
    statusRailDivider: {
        color: homeDashboardColors.lineStrong,
        fontSize: homeDashboardTypography.caption,
        fontWeight: '900',
        lineHeight: 16,
    },
    summaryPanel: {
        borderRadius: homeDashboardRadii.xl,
        borderCurve: 'continuous',
        borderWidth: 1,
        borderColor: homeDashboardColors.line,
        backgroundColor: homeDashboardColors.surfaceStrong,
        marginTop: homeDashboardSpacing.md,
        marginBottom: homeDashboardSpacing.xl,
        overflow: 'hidden',
        padding: homeDashboardSpacing.lg,
        position: 'relative',
        boxShadow: homeDashboardShadows.card,
    },
    summaryPanelContent: {
        gap: homeDashboardSpacing.md,
        zIndex: 1,
    },
    summaryPanelHeader: {
        gap: homeDashboardSpacing.xs,
    },
    summaryEyebrow: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.caption,
        fontWeight: '800',
        letterSpacing: 0.7,
        lineHeight: 15,
        textTransform: 'uppercase',
    },
    summaryTitle: {
        color: homeDashboardColors.ink,
        fontSize: 25,
        fontWeight: '900',
        letterSpacing: 0,
        lineHeight: 30,
    },
    summaryDescription: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.body,
        fontWeight: '500',
        lineHeight: 21,
    },
    summaryMetricRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: homeDashboardSpacing.xs,
    },
    summaryMetricPill: {
        backgroundColor: homeDashboardColors.surfaceMuted,
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.pill,
        borderWidth: 1,
        minHeight: 32,
        paddingHorizontal: homeDashboardSpacing.sm,
        justifyContent: 'center',
    },
    summaryMetricText: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.caption,
        fontWeight: '800',
        letterSpacing: 0.4,
        lineHeight: 14,
        textTransform: 'uppercase',
    },
    editActionRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: homeDashboardSpacing.sm,
    },
    editActionButton: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.ink,
        borderColor: homeDashboardColors.ink,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.pill,
        borderWidth: 1,
        flexDirection: 'row',
        gap: homeDashboardSpacing.xs,
        justifyContent: 'center',
        minHeight: 44,
        paddingHorizontal: homeDashboardSpacing.md,
    },
    editActionButtonSecondary: {
        backgroundColor: homeDashboardColors.surfaceMuted,
        borderColor: homeDashboardColors.lineStrong,
    },
    editActionText: {
        color: homeDashboardColors.paper,
        fontSize: homeDashboardTypography.bodyStrong,
        fontWeight: '800',
        lineHeight: 18,
    },
    editActionTextSecondary: {
        color: homeDashboardColors.ink,
    },
    heroSection: {
        marginTop: 8,
        marginBottom: 24,
    },
    heroTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        marginBottom: 8,
    },
    heroSubtitle: {
        fontSize: 16,
        lineHeight: 22,
    },
    sectionHeader: {
        color: homeDashboardColors.ink,
        fontSize: homeDashboardTypography.bodyStrong,
        fontWeight: '900',
        lineHeight: 20,
        marginBottom: homeDashboardSpacing.xs,
    },
    sectionSubtext: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.body,
        fontWeight: '500',
        lineHeight: 20,
        marginBottom: homeDashboardSpacing.sm,
    },
    sectionTitleRow: {
        alignItems: 'flex-start',
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: homeDashboardSpacing.sm,
    },
    ledgerSection: {
        marginBottom: homeDashboardSpacing.xl,
    },
    ledgerList: {
        gap: homeDashboardSpacing.sm,
    },
    ledgerRow: {
        alignItems: 'stretch',
        backgroundColor: homeDashboardColors.surfaceStrong,
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.lg,
        borderWidth: 1,
        flexDirection: 'row',
        overflow: 'hidden',
    },
    ledgerMainButton: {
        alignItems: 'center',
        flex: 1,
        flexDirection: 'row',
        gap: homeDashboardSpacing.sm,
        justifyContent: 'space-between',
        minHeight: 64,
        paddingHorizontal: homeDashboardSpacing.md,
        paddingVertical: homeDashboardSpacing.sm,
    },
    ledgerItemTextGroup: {
        flex: 1,
        gap: 2,
        minWidth: 0,
    },
    ledgerItemName: {
        color: homeDashboardColors.ink,
        fontSize: homeDashboardTypography.bodyStrong,
        fontWeight: '900',
        lineHeight: 20,
    },
    ledgerItemKind: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.caption,
        fontWeight: '700',
        lineHeight: 16,
    },
    inlineSeverityPill: {
        alignItems: 'center',
        borderRadius: homeDashboardRadii.pill,
        borderWidth: 1,
        flexDirection: 'row',
        gap: homeDashboardSpacing.xxs,
        minHeight: 34,
        paddingHorizontal: homeDashboardSpacing.sm,
    },
    inlineSeverityText: {
        fontSize: homeDashboardTypography.caption,
        fontWeight: '900',
        lineHeight: 15,
    },
    ledgerRemoveButton: {
        alignItems: 'center',
        borderLeftColor: homeDashboardColors.line,
        borderLeftWidth: 1,
        justifyContent: 'center',
        minHeight: 64,
        minWidth: 48,
    },
    emptyLedgerCard: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.surfaceMuted,
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.lg,
        borderWidth: 1,
        flexDirection: 'row',
        gap: homeDashboardSpacing.sm,
        minHeight: 76,
        padding: homeDashboardSpacing.md,
    },
    emptyLedgerTextGroup: {
        flex: 1,
        gap: 2,
    },
    emptyLedgerTitle: {
        color: homeDashboardColors.ink,
        fontSize: homeDashboardTypography.bodyStrong,
        fontWeight: '900',
        lineHeight: 20,
    },
    emptyLedgerBody: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.body,
        fontWeight: '500',
        lineHeight: 20,
    },
    editorSection: {
        marginBottom: homeDashboardSpacing.xl,
    },
    searchToggleButton: {
        alignItems: 'center',
        alignSelf: 'flex-start',
        borderColor: homeDashboardColors.lineStrong,
        borderRadius: homeDashboardRadii.pill,
        borderWidth: 1,
        flexDirection: 'row',
        gap: homeDashboardSpacing.xs,
        minHeight: 44,
        paddingHorizontal: homeDashboardSpacing.md,
        paddingVertical: homeDashboardSpacing.xs,
    },
    searchToggleText: {
        color: homeDashboardColors.ink,
        fontSize: 15,
        fontWeight: '800',
        lineHeight: 18,
    },
    severityHint: {
        fontSize: 13,
        marginBottom: 12,
    },
    severitySegmentRow: {
        flexDirection: 'row',
        gap: 6,
        marginTop: 12,
    },
    severitySegment: {
        alignItems: 'center',
        borderRadius: homeDashboardRadii.pill,
        borderWidth: 1,
        flex: 1,
        minHeight: 36,
        justifyContent: 'center',
        paddingHorizontal: 8,
    },
    severitySegmentText: {
        fontSize: 12,
        fontWeight: '800',
        lineHeight: 14,
    },
    severityRow: {
        alignItems: 'stretch',
        padding: 14,
        borderRadius: 20,
        marginBottom: 8,
        borderWidth: 1,
    },
    severityAllergenName: {
        fontSize: 16,
        fontWeight: '600',
    },
    severityRowHeader: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 12,
        justifyContent: 'space-between',
    },
    severityBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        borderWidth: 1,
        gap: 4,
    },
    severityBadgeText: {
        fontSize: 13,
        fontWeight: '700',
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        rowGap: homeDashboardSpacing.sm,
    },
    card: {
        alignItems: 'center',
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.lg,
        borderWidth: 1,
        boxShadow: homeDashboardShadows.card,
        flexBasis: '48%',
        flexDirection: 'row',
        gap: homeDashboardSpacing.sm,
        justifyContent: 'space-between',
        minHeight: 86,
        overflow: 'hidden',
        paddingHorizontal: homeDashboardSpacing.sm,
        paddingVertical: homeDashboardSpacing.md,
    },
    cardUnselected: {
        backgroundColor: homeDashboardColors.surfaceStrong,
    },
    cardSelected: {
        backgroundColor: homeDashboardColors.accentGreenSoft,
        borderColor: homeDashboardColors.accentGreen,
    },
    iconCircle: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.pearlIvory,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.md,
        justifyContent: 'center',
        minHeight: 48,
        minWidth: 48,
    },
    iconCircleSelected: {
        backgroundColor: homeDashboardColors.pearlGlow,
    },
    cardIconImage: {
        height: 38,
        width: 38,
    },
    cardLabel: {
        flex: 1,
        flexShrink: 1,
        fontSize: 16,
        fontWeight: '900',
        lineHeight: 20,
        minWidth: 0,
    },
    cardLabelUnselected: {
        color: homeDashboardColors.ink,
    },
    cardLabelSelected: {
        color: homeDashboardColors.accentGreen,
    },
    cardCheckSlot: {
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 24,
        width: 24,
    },
    checkBadge: {
        backgroundColor: homeDashboardColors.pearlIvory,
        alignItems: 'center',
        borderRadius: 12,
        height: 24,
        justifyContent: 'center',
        width: 24,
    },
    inputSection: {
        zIndex: 10,
    },
    inputWrapper: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.surfaceStrong,
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.lg,
        borderWidth: 1,
        boxShadow: homeDashboardShadows.card,
        flexDirection: 'row',
        gap: homeDashboardSpacing.sm,
        marginBottom: homeDashboardSpacing.sm,
        minHeight: 72,
        overflow: 'hidden',
        paddingHorizontal: homeDashboardSpacing.sm,
        paddingVertical: homeDashboardSpacing.sm,
    },
    inputIconSlot: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.pearlIvory,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.md,
        justifyContent: 'center',
        minHeight: 48,
        minWidth: 48,
    },
    input: {
        color: homeDashboardColors.ink,
        flex: 1,
        fontSize: 16,
        fontWeight: '800',
        lineHeight: 20,
        minHeight: 44,
        minWidth: 0,
    },
    inputActionSlot: {
        alignItems: 'center',
        justifyContent: 'center',
        minHeight: 44,
        width: 44,
    },
    inputActionButton: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.pearlIvory,
        borderRadius: homeDashboardRadii.pill,
        height: 44,
        justifyContent: 'center',
        width: 44,
    },
    tagContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    tag: {
        backgroundColor: homeDashboardColors.surfaceMuted,
        borderRadius: homeDashboardRadii.pill,
        paddingHorizontal: homeDashboardSpacing.md,
        paddingVertical: homeDashboardSpacing.xs,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
    },
    tagText: {
        fontWeight: '600',
        fontSize: 14,
    },
    footer: {
        backgroundColor: homeDashboardColors.surfaceStrong,
        borderColor: homeDashboardColors.line,
        borderTopWidth: 1,
        padding: homeDashboardSpacing.lg,
        paddingBottom: Platform.OS === 'ios' ? 30 : 20,
        gap: homeDashboardSpacing.sm,
    },
    footerStatusText: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.caption,
        fontWeight: '800',
        lineHeight: 16,
        textAlign: 'center',
        textTransform: 'uppercase',
    },
    saveButton: {
        backgroundColor: homeDashboardColors.ink,
        borderRadius: homeDashboardRadii.pill,
        minHeight: 52,
        justifyContent: 'center',
        paddingVertical: homeDashboardSpacing.md,
        alignItems: 'center',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
    },
    saveButtonText: {
        color: homeDashboardColors.paper,
        fontSize: homeDashboardTypography.bodyStrong,
        fontWeight: '900',
        lineHeight: 18,
    },
    logoutButton: {
        marginTop: 12,
        borderRadius: 20,
        paddingVertical: 14,
        alignItems: 'center',
        borderWidth: 1,
        backgroundColor: 'transparent',
    },
    logoutButtonText: {
        fontSize: 15,
        fontWeight: '700',
    },
    suggestionsDropdown: {
        backgroundColor: homeDashboardColors.surfaceStrong,
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.lg,
        borderWidth: 1,
        boxShadow: homeDashboardShadows.card,
        marginBottom: homeDashboardSpacing.sm,
        overflow: 'hidden',
        paddingVertical: homeDashboardSpacing.xs,
    },
    suggestionItem: {
        alignItems: 'center',
        borderBottomWidth: 0.5,
        flexDirection: 'row',
        gap: homeDashboardSpacing.sm,
        minHeight: 58,
        paddingHorizontal: homeDashboardSpacing.sm,
        paddingVertical: homeDashboardSpacing.xs,
    },
    suggestionIconSlot: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.pearlIvory,
        borderRadius: homeDashboardRadii.pill,
        height: 36,
        justifyContent: 'center',
        width: 36,
    },
    suggestionText: {
        color: homeDashboardColors.ink,
        flex: 1,
        flexShrink: 1,
        fontSize: 16,
        fontWeight: '900',
        lineHeight: 20,
        minWidth: 0,
    },
    savedToastOverlay: {
        alignItems: 'center',
        justifyContent: 'center',
        left: 0,
        position: 'absolute',
        right: 0,
        top: '50%',
        zIndex: 20,
    },
    savedToast: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.surfaceStrong,
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.pill,
        borderWidth: 1,
        boxShadow: homeDashboardShadows.card,
        flexDirection: 'row',
        gap: homeDashboardSpacing.xs,
        minHeight: 44,
        paddingHorizontal: homeDashboardSpacing.md,
    },
    savedToastIcon: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.pearlIvory,
        borderRadius: homeDashboardRadii.pill,
        height: 24,
        justifyContent: 'center',
        width: 24,
    },
    savedToastText: {
        color: homeDashboardColors.ink,
        fontSize: homeDashboardTypography.bodyStrong,
        fontWeight: '900',
        lineHeight: 18,
    },
});
