import { StyleSheet, Platform } from 'react-native';

import {
    homeDashboardColors,
    homeDashboardRadii,
    homeDashboardShadows,
    homeDashboardSpacing,
    homeDashboardTypography,
} from '../../home/components/homeDashboardTokens';

export const profileStyles = StyleSheet.create({
    safeArea: {
        flex: 1,
        backgroundColor: homeDashboardColors.paper,
    },
    navBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingVertical: 15,
    },
    navButton: {
        padding: 5,
    },
    navTitle: {
        fontSize: 17,
        fontWeight: '600',
    },
    container: {
        flex: 1,
        paddingHorizontal: 20,
    },
    summaryPanel: {
        borderRadius: homeDashboardRadii.xl,
        borderCurve: 'continuous',
        borderWidth: 1,
        borderColor: homeDashboardColors.line,
        backgroundColor: homeDashboardColors.surfaceStrong,
        marginTop: 18,
        marginBottom: 24,
        overflow: 'hidden',
        padding: homeDashboardSpacing.lg,
        position: 'relative',
        boxShadow: homeDashboardShadows.card,
    },
    summaryPanelContent: {
        gap: homeDashboardSpacing.md,
        zIndex: 1,
    },
    summaryPanelHeader: {
        gap: homeDashboardSpacing.xs,
    },
    summaryEyebrow: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.caption,
        fontWeight: '800',
        letterSpacing: 0.7,
        lineHeight: 15,
        textTransform: 'uppercase',
    },
    summaryTitle: {
        color: homeDashboardColors.ink,
        fontSize: 25,
        fontWeight: '900',
        letterSpacing: -0.5,
        lineHeight: 30,
    },
    summaryDescription: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.body,
        fontWeight: '500',
        lineHeight: 21,
    },
    summaryMetricRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: homeDashboardSpacing.xs,
    },
    summaryMetricPill: {
        backgroundColor: homeDashboardColors.surfaceMuted,
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.pill,
        borderWidth: 1,
        minHeight: 32,
        paddingHorizontal: homeDashboardSpacing.sm,
        justifyContent: 'center',
    },
    summaryMetricText: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.caption,
        fontWeight: '800',
        letterSpacing: 0.4,
        lineHeight: 14,
        textTransform: 'uppercase',
    },
    editActionRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: homeDashboardSpacing.sm,
    },
    editActionButton: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.ink,
        borderColor: homeDashboardColors.ink,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.pill,
        borderWidth: 1,
        flexDirection: 'row',
        gap: homeDashboardSpacing.xs,
        justifyContent: 'center',
        minHeight: 44,
        paddingHorizontal: homeDashboardSpacing.md,
    },
    editActionButtonSecondary: {
        backgroundColor: homeDashboardColors.surfaceMuted,
        borderColor: homeDashboardColors.lineStrong,
    },
    editActionText: {
        color: homeDashboardColors.paper,
        fontSize: homeDashboardTypography.bodyStrong,
        fontWeight: '800',
        lineHeight: 18,
    },
    editActionTextSecondary: {
        color: homeDashboardColors.ink,
    },
    heroSection: {
        marginTop: 8,
        marginBottom: 24,
    },
    heroTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        marginBottom: 8,
    },
    heroSubtitle: {
        fontSize: 16,
        lineHeight: 22,
    },
    sectionHeader: {
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 15,
        marginTop: 10,
    },
    searchToggleButton: {
        alignSelf: 'flex-start',
        borderColor: homeDashboardColors.lineStrong,
        borderRadius: homeDashboardRadii.pill,
        borderWidth: 1,
        paddingVertical: 10,
        paddingHorizontal: 14,
    },
    searchToggleText: {
        fontSize: 15,
        fontWeight: '600',
    },
    severityHint: {
        fontSize: 13,
        marginBottom: 12,
    },
    severitySegmentRow: {
        flexDirection: 'row',
        gap: 6,
        marginTop: 12,
    },
    severitySegment: {
        alignItems: 'center',
        borderRadius: homeDashboardRadii.pill,
        borderWidth: 1,
        flex: 1,
        minHeight: 36,
        justifyContent: 'center',
        paddingHorizontal: 8,
    },
    severitySegmentText: {
        fontSize: 12,
        fontWeight: '800',
        lineHeight: 14,
    },
    severityRow: {
        alignItems: 'stretch',
        padding: 14,
        borderRadius: 20,
        marginBottom: 8,
        borderWidth: 1,
    },
    severityAllergenName: {
        fontSize: 16,
        fontWeight: '600',
    },
    severityRowHeader: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: 12,
        justifyContent: 'space-between',
    },
    severityBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        borderWidth: 1,
        gap: 4,
    },
    severityBadgeText: {
        fontSize: 13,
        fontWeight: '700',
    },
    grid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: 12,
    },
    card: {
        width: '48%',
        borderRadius: 20,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    iconCircle: {
        width: 40,
        height: 40,
        borderRadius: 12,
        backgroundColor: 'transparent',
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    cardLabel: {
        fontSize: 16,
        fontWeight: '600',
    },
    checkBadge: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: 'white',
        borderRadius: 10,
        width: 18,
        height: 18,
        alignItems: 'center',
        justifyContent: 'center',
    },
    inputWrapper: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 16,
        paddingHorizontal: 15,
        paddingVertical: 14,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 1,
        marginBottom: 20,
    },
    input: {
        flex: 1,
        fontSize: 16,
    },
    tagContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 10,
    },
    tag: {
        backgroundColor: '#E6F0FF',
        borderRadius: 100,
        paddingHorizontal: 16,
        paddingVertical: 10,
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
    },
    tagText: {
        fontWeight: '600',
        fontSize: 14,
    },
    footer: {
        padding: 20,
        paddingBottom: Platform.OS === 'ios' ? 30 : 20,
        borderTopWidth: 1,
    },
    saveButton: {
        borderRadius: 24,
        paddingVertical: 18,
        alignItems: 'center',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
    },
    saveButtonText: {
        color: 'white',
        fontSize: 18,
        fontWeight: 'bold',
    },
    logoutButton: {
        marginTop: 12,
        borderRadius: 20,
        paddingVertical: 14,
        alignItems: 'center',
        borderWidth: 1,
        backgroundColor: 'transparent',
    },
    logoutButtonText: {
        fontSize: 15,
        fontWeight: '700',
    },
    suggestionsDropdown: {
        marginTop: 8,
        backgroundColor: 'white',
        borderRadius: 16,
        paddingVertical: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
        borderWidth: 1,
        marginBottom: 20,
    },
    suggestionItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderBottomWidth: 0.5,
    },
    suggestionText: {
        fontSize: 16,
    },
});
