import { StyleSheet } from 'react-native';

import { Colors } from '@/constants/theme';
import {
    homeDashboardColors,
    homeDashboardRadii,
    homeDashboardShadows,
    homeDashboardSpacing,
    homeDashboardTypography,
} from '../../home/components/homeDashboardTokens';

export const supportPoliciesStyles = StyleSheet.create({
    root: {
        flex: 1,
        backgroundColor: homeDashboardColors.paper,
    },
    darkRoot: {
        backgroundColor: Colors.dark.background,
    },
    scroll: {
        flex: 1,
    },
    scrollContent: {
        gap: homeDashboardSpacing.lg,
        paddingHorizontal: homeDashboardSpacing.lg,
        paddingTop: homeDashboardSpacing.sm,
    },
    darkPanel: {
        backgroundColor: Colors.dark.surface,
        borderColor: Colors.dark.border,
        boxShadow: 'none',
    },
    darkMutedPanel: {
        backgroundColor: Colors.dark.surface,
        borderColor: Colors.dark.border,
    },
    darkPrimaryAction: {
        backgroundColor: Colors.dark.background,
        borderColor: Colors.dark.border,
    },
    darkPrimaryTitle: {
        color: Colors.dark.textPrimary,
    },
    darkPrimaryDescription: {
        color: Colors.dark.textSecondary,
    },
    darkPrimaryIconWrap: {
        backgroundColor: 'rgba(255, 255, 255, 0.08)',
    },
    darkSecondaryIconWrap: {
        backgroundColor: 'rgba(34, 197, 94, 0.12)',
    },
    darkCompactRowBorder: {
        borderBottomColor: Colors.dark.border,
        borderBottomWidth: 1,
    },
    darkTextPrimary: {
        color: Colors.dark.textPrimary,
    },
    darkTextSecondary: {
        color: Colors.dark.textSecondary,
    },
    section: {
        gap: homeDashboardSpacing.sm,
    },
    sectionTitle: {
        color: homeDashboardColors.inkSoft,
        fontSize: homeDashboardTypography.caption,
        fontWeight: '800',
        letterSpacing: 0.7,
        lineHeight: 16,
        textTransform: 'uppercase',
    },
    supportSurface: {
        backgroundColor: homeDashboardColors.surfaceStrong,
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.xl,
        borderWidth: 1,
        boxShadow: homeDashboardShadows.hero,
        gap: homeDashboardSpacing.sm,
        overflow: 'hidden',
        padding: homeDashboardSpacing.md,
        position: 'relative',
    },
    surfaceContent: {
        gap: homeDashboardSpacing.sm,
        zIndex: 1,
    },
    primaryAction: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.ink,
        borderColor: homeDashboardColors.ink,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.lg,
        borderWidth: 1,
        flexDirection: 'row',
        gap: homeDashboardSpacing.sm,
        justifyContent: 'space-between',
        minHeight: 72,
        paddingHorizontal: homeDashboardSpacing.md,
        paddingVertical: homeDashboardSpacing.sm,
    },
    secondaryAction: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.surfaceMuted,
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.md,
        borderWidth: 1,
        flexDirection: 'row',
        gap: homeDashboardSpacing.sm,
        justifyContent: 'space-between',
        minHeight: 60,
        paddingHorizontal: homeDashboardSpacing.md,
        paddingVertical: homeDashboardSpacing.sm,
    },
    rowCopy: {
        flex: 1,
        flexShrink: 1,
        gap: homeDashboardSpacing.xxs,
        minWidth: 0,
    },
    primaryTitle: {
        color: homeDashboardColors.paper,
        flexShrink: 1,
        fontSize: 18,
        fontWeight: '900',
        lineHeight: 23,
    },
    primaryDescription: {
        color: homeDashboardColors.paperStrong,
        flexShrink: 1,
        fontSize: homeDashboardTypography.body,
        fontWeight: '600',
        lineHeight: 20,
    },
    secondaryTitle: {
        color: homeDashboardColors.ink,
        flexShrink: 1,
        fontSize: homeDashboardTypography.bodyStrong,
        fontWeight: '800',
        lineHeight: 20,
    },
    secondaryDescription: {
        color: homeDashboardColors.inkSoft,
        flexShrink: 1,
        fontSize: homeDashboardTypography.body,
        fontWeight: '500',
        lineHeight: 20,
    },
    primaryIconWrap: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.pearlGlow,
        borderRadius: homeDashboardRadii.pill,
        height: 36,
        justifyContent: 'center',
        width: 36,
    },
    secondaryIconWrap: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.accentGreenSoft,
        borderRadius: homeDashboardRadii.pill,
        height: 34,
        justifyContent: 'center',
        width: 34,
    },
    rowIcon: {
        flexShrink: 0,
    },
    compactGroup: {
        backgroundColor: homeDashboardColors.surfaceStrong,
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.lg,
        borderWidth: 1,
        boxShadow: homeDashboardShadows.card,
        overflow: 'hidden',
    },
    compactRow: {
        alignItems: 'center',
        flexDirection: 'row',
        gap: homeDashboardSpacing.sm,
        justifyContent: 'space-between',
        minHeight: 54,
        paddingHorizontal: homeDashboardSpacing.md,
        paddingVertical: homeDashboardSpacing.sm,
    },
    compactRowBorder: {
        borderBottomColor: homeDashboardColors.line,
        borderBottomWidth: 1,
    },
    compactLabel: {
        color: homeDashboardColors.ink,
        flex: 1,
        flexShrink: 1,
        fontSize: homeDashboardTypography.bodyStrong,
        fontWeight: '800',
        lineHeight: 20,
        minWidth: 0,
    },
    neutralRow: {
        alignItems: 'center',
        backgroundColor: homeDashboardColors.surfaceMuted,
        borderColor: homeDashboardColors.line,
        borderCurve: 'continuous',
        borderRadius: homeDashboardRadii.lg,
        borderWidth: 1,
        boxShadow: homeDashboardShadows.card,
        flexDirection: 'row',
        gap: homeDashboardSpacing.sm,
        justifyContent: 'space-between',
        minHeight: 64,
        paddingHorizontal: homeDashboardSpacing.md,
        paddingVertical: homeDashboardSpacing.sm,
    },
});
