import { StyleSheet } from 'react-native';

export const analysisLoadingStyles = StyleSheet.create({
    container: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 100,
        backgroundColor: 'black',
    },
    backgroundLayer: {
        ...StyleSheet.absoluteFillObject,
    },
    backgroundImage: {
        width: '100%',
        height: '100%',
        opacity: 1,
    },
    darkOverlay: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(2, 6, 23, 0.85)',
    },
    coreContainer: {
        alignItems: 'center',
        justifyContent: 'center',
    },
    orbitRing: {
        position: 'absolute',
        width: 250,
        height: 250,
        borderRadius: 125,
        borderWidth: 1,
        borderStyle: 'dashed',
    },
    orbitRingInner: {
        position: 'absolute',
        width: 200,
        height: 200,
        borderRadius: 100,
        borderWidth: 1,
        borderStyle: 'dotted',
    },
    ripple: {
        position: 'absolute',
        width: 150,
        height: 150,
        borderRadius: 75,
        borderWidth: 2,
    },
    hub: {
        width: 100,
        height: 100,
        borderRadius: 50,
        borderWidth: 1,
        overflow: 'hidden',
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    hubBlur: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    iconCircle: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: 'white',
        shadowOpacity: 0.5,
        shadowRadius: 10,
        elevation: 10,
    },
    hudContainer: {
        position: 'absolute',
        top: 60,
        bottom: 50,
        alignItems: 'center',
        width: '100%',
    },
    statusBadge: {
        paddingHorizontal: 16,
        paddingVertical: 6,
        borderRadius: 20,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.1)',
        backgroundColor: 'rgba(255,255,255,0.05)',
    },
    statusText: {
        color: 'rgba(255,255,255,0.5)',
        fontSize: 10,
        fontWeight: '900',
        letterSpacing: 2,
    },
    messageArea: {
        alignItems: 'center',
        width: '80%',
        marginBottom: 60,
    },
    mainMessage: {
        color: 'white',
        fontSize: 14,
        fontWeight: 'bold',
        letterSpacing: 3,
        textTransform: 'uppercase',
        marginBottom: 10,
    },
    loadingDots: {
        flexDirection: 'row',
        gap: 4,
        marginBottom: 20,
    },
    dot: {
        width: 4,
        height: 4,
        borderRadius: 2,
        backgroundColor: '#60A5FA',
    },
    progressBarBg: {
        width: '100%',
        height: 2,
        backgroundColor: 'rgba(255,255,255,0.1)',
        borderRadius: 2,
        overflow: 'hidden',
    },
    progressBarFill: {
        height: '100%',
        backgroundColor: '#3B82F6',
    },
    cancelButton: {
        alignItems: 'center',
        gap: 12,
    },
    cancelIconCircle: {
        width: 44,
        height: 44,
        borderRadius: 22,
        borderWidth: 1,
        borderColor: 'rgba(255,255,255,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    cancelText: {
        color: 'rgba(255,255,255,0.4)',
        fontSize: 10,
        fontWeight: 'bold',
        letterSpacing: 2,
    },
});
