declare namespace NodeJS {
  interface ProcessEnv {
    EXPO_PUBLIC_AI_ASYNC_ANALYZE_ENABLED?: string;
    EXPO_PUBLIC_AI_CACHE_TTL_SECONDS?: string;
    EXPO_PUBLIC_ANALYSIS_SERVER_URL?: string;
    EXPO_PUBLIC_AUTH_GOOGLE_LOGOUT_START_URL?: string;
    EXPO_PUBLIC_AUTH_GOOGLE_START_URL?: string;
    EXPO_PUBLIC_AUTH_KAKAO_BROWSER_LOGOUT_ENABLED?: string;
    EXPO_PUBLIC_AUTH_KAKAO_LOGOUT_START_URL?: string;
    EXPO_PUBLIC_AUTH_KAKAO_START_URL?: string;
    EXPO_PUBLIC_AUTH_OAUTH_MODE?: string;
    EXPO_PUBLIC_GOOGLE_MAPS_API_KEY?: string;
    EXPO_PUBLIC_LOCATION_TIMEOUT_MS?: string;
    EXPO_PUBLIC_OAUTH_CUSTOM_REDIRECT_SCHEME?: string;
    EXPO_PUBLIC_OAUTH_REDIRECT_BASE_URL?: string;
    EXPO_PUBLIC_OAUTH_REDIRECT_TRANSPORT?: string;
    EXPO_PUBLIC_ONBOARDING_PREVIEW_ENABLED?: string;
    EXPO_PUBLIC_PHASE2_FORCE_WRITE_PROBE?: string;
    EXPO_PUBLIC_SENTRY_DSN?: string;
    EXPO_PUBLIC_SUPPORT_EMAIL?: string;
  }
}
