export const FLOATING_BOTTOM_NAV_HEIGHT = 58;
export const FLOATING_BOTTOM_NAV_BOTTOM_OFFSET = 0;
export const FLOATING_BOTTOM_NAV_CLEARANCE = 124;
export const FLOATING_BOTTOM_NAV_SLOT_WIDTH = 68;
export const FLOATING_BOTTOM_NAV_HORIZONTAL_PADDING = 0;
export const FLOATING_BOTTOM_NAV_MAX_WIDTH =
  FLOATING_BOTTOM_NAV_SLOT_WIDTH * 5 + FLOATING_BOTTOM_NAV_HORIZONTAL_PADDING * 2;
export const FLOATING_BOTTOM_NAV_ICON_SIZE = 22;
export const FLOATING_BOTTOM_NAV_LABEL_SIZE = 10;
export const FLOATING_BOTTOM_NAV_ICON_SURFACE_SIZE = 22;
export const FLOATING_BOTTOM_NAV_SCAN_SURFACE_SIZE = 22;

export type FloatingBottomNavItemKey = 'home' | 'history' | 'allergies' | 'profile';
