import { Platform } from 'react-native';

const IS_ANDROID = Platform.OS === 'android';

export const FLOATING_BOTTOM_NAV_ANDROID_HEIGHT = 58;
export const FLOATING_BOTTOM_NAV_HEIGHT = IS_ANDROID ? FLOATING_BOTTOM_NAV_ANDROID_HEIGHT : 68;
export const FLOATING_BOTTOM_NAV_BOTTOM_OFFSET = IS_ANDROID ? 0 : 8;
export const FLOATING_BOTTOM_NAV_CLEARANCE = IS_ANDROID ? 124 : 136;
export const FLOATING_BOTTOM_NAV_SLOT_WIDTH = IS_ANDROID ? 68 : 68;
export const FLOATING_BOTTOM_NAV_HORIZONTAL_PADDING = IS_ANDROID ? 0 : 10;
export const FLOATING_BOTTOM_NAV_MAX_WIDTH =
  FLOATING_BOTTOM_NAV_SLOT_WIDTH * 5 + FLOATING_BOTTOM_NAV_HORIZONTAL_PADDING * 2;
export const FLOATING_BOTTOM_NAV_ICON_SIZE = 22;
export const FLOATING_BOTTOM_NAV_LABEL_SIZE = 10;
export const FLOATING_BOTTOM_NAV_ICON_SURFACE_SIZE = IS_ANDROID ? 28 : 32;
export const FLOATING_BOTTOM_NAV_SCAN_SURFACE_SIZE = IS_ANDROID ? 30 : 34;

export type FloatingBottomNavItemKey = 'home' | 'history' | 'allergies' | 'profile';
