import { StyleSheet } from 'react-native';
import { LOGIN_COLORS, LOGIN_LAYOUT } from '../constants/login.constants';

export const loginStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: LOGIN_COLORS.phoneBackground,
  },
  root: {
    flex: 1,
  },
  rootFramed: {
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
  },
  rootFull: {
    justifyContent: 'flex-start',
    alignItems: 'stretch',
    paddingHorizontal: 0,
    paddingVertical: 0,
  },
  phoneContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: LOGIN_COLORS.phoneBackground,
    position: 'relative',
    overflow: 'hidden',
  },
  phoneContainerFramed: {
    width: LOGIN_LAYOUT.phoneMaxWidth,
    height: LOGIN_LAYOUT.phoneMaxHeight,
    maxWidth: LOGIN_LAYOUT.phoneMaxWidth,
    maxHeight: LOGIN_LAYOUT.phoneMaxHeight,
    borderRadius: 40,
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 25 },
    shadowOpacity: 0.25,
    shadowRadius: 24,
    elevation: 15,
  },
  phoneContainerCompact: {
    width: '100%',
    height: '100%',
    borderRadius: 0,
    shadowOpacity: 0,
    elevation: 0,
  },
  pinkHeader: {
    position: 'absolute',
    top: LOGIN_LAYOUT.pinkHeaderTop,
    left: 0,
    right: 0,
    height: `${LOGIN_LAYOUT.pinkHeaderHeightPercent * 100}%`,
    backgroundColor: LOGIN_COLORS.accent,
    zIndex: 10,
  },
  patternOverlay: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.4,
  },
  waveBottom: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: -1,
    height: 150,
  },
  screen: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    paddingTop: 0,
    paddingHorizontal: LOGIN_LAYOUT.screenHorizontalPadding,
    paddingBottom: 0,
    zIndex: 20,
  },
  welcomeTitle: {
    marginTop: 524,
    fontSize: 42,
    fontWeight: '700',
    color: LOGIN_COLORS.textPrimary,
  },
  welcomeDescription: {
    marginTop: 16,
    color: LOGIN_COLORS.textSecondary,
    fontSize: 16,
    lineHeight: 24,
  },
  continueButtonContainer: {
    position: 'absolute',
    right: LOGIN_LAYOUT.screenHorizontalPadding,
    bottom: 60,
  },
  continueButtonPressable: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  continueText: {
    color: LOGIN_COLORS.textSecondary,
    fontWeight: '600',
    marginRight: 12,
  },
  arrowCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: LOGIN_COLORS.accent,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: LOGIN_COLORS.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 6,
  },
  authContainer: {
    marginTop: LOGIN_LAYOUT.authMarginTopLogin,
  },
  authTitleWrap: {
    marginBottom: 30,
  },
  authTitle: {
    fontSize: 36,
    fontWeight: '700',
    color: LOGIN_COLORS.textPrimary,
  },
  authTitleUnderline: {
    marginTop: 8,
    width: 60,
    height: 4,
    borderRadius: 2,
    backgroundColor: LOGIN_COLORS.accent,
  },
  inputGroup: {
    borderBottomWidth: 1.5,
    borderBottomColor: LOGIN_COLORS.border,
    paddingBottom: 8,
    marginBottom: 20,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#666666',
    marginBottom: 8,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  inputPipe: {
    color: LOGIN_COLORS.inputPipe,
    marginRight: 4,
    marginLeft: 8,
  },
  inputField: {
    flex: 1,
    fontSize: 15,
    color: LOGIN_COLORS.textPrimary,
    paddingVertical: 2,
  },
  eyeButton: {
    marginLeft: 8,
    padding: 2,
  },
  collapsibleField: {
    overflow: 'hidden',
    borderBottomColor: LOGIN_COLORS.border,
  },
  loginActionRow: {
    overflow: 'hidden',
  },
  actionRowInner: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  checkboxGroup: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  checkboxRect: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: LOGIN_COLORS.accent,
    marginRight: 6,
  },
  checkboxRectChecked: {
    backgroundColor: LOGIN_COLORS.accent,
  },
  checkboxText: {
    color: LOGIN_COLORS.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  forgotText: {
    color: LOGIN_COLORS.accent,
    fontWeight: '600',
    fontSize: 13,
  },
  authFooter: {
    position: 'absolute',
    left: LOGIN_LAYOUT.screenHorizontalPadding,
    right: LOGIN_LAYOUT.screenHorizontalPadding,
    bottom: 60,
    zIndex: 30,
  },
  errorText: {
    color: '#b91c1c',
    fontSize: 13,
    marginBottom: 10,
  },
  infoText: {
    color: LOGIN_COLORS.textSecondary,
    fontSize: 13,
    marginBottom: 10,
  },
  verificationFieldWrap: {
    marginTop: 10,
  },
  primaryButton: {
    width: '100%',
    backgroundColor: LOGIN_COLORS.accent,
    borderRadius: 12,
    paddingVertical: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: LOGIN_COLORS.accent,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 20,
    elevation: 8,
  },
  primaryButtonLabel: {
    color: LOGIN_COLORS.white,
    fontSize: 18,
    fontWeight: '700',
  },
  oauthDivider: {
    marginTop: 18,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
  },
  oauthDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#e2e8f0',
  },
  oauthDividerText: {
    marginHorizontal: 12,
    color: '#94a3b8',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  oauthButtonGroup: {
    marginTop: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 14,
  },
  oauthButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    borderWidth: 1,
    borderColor: '#f0f0f0',
    backgroundColor: LOGIN_COLORS.white,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  oauthGoogleButton: {
    backgroundColor: LOGIN_COLORS.white,
    borderColor: '#e5e7eb',
  },
  oauthKakaoButton: {
    backgroundColor: '#FEE500',
    borderColor: '#FEE500',
  },
  switchAuthRow: {
    marginTop: 20,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  switchAuthLead: {
    fontSize: 14,
    color: LOGIN_COLORS.textSecondary,
  },
  switchAuthAction: {
    marginLeft: 4,
    fontSize: 14,
    color: LOGIN_COLORS.accent,
    fontWeight: '700',
  },
});
