import { StyleSheet } from 'react-native';

import {
    allergiesDashboardColors,
    allergiesDashboardRadii,
    allergiesDashboardShadows,
    allergiesDashboardSpacing,
    allergiesDashboardTypography,
} from './allergiesDashboardTokens';

export const allergiesDashboardStyles = StyleSheet.create({
    screenBackground: {
        flex: 1,
        backgroundColor: allergiesDashboardColors.paper,
    },
    screenAtmosphere: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: allergiesDashboardColors.paper,
        opacity: 1,
    },
    grainLayer: {
        ...StyleSheet.absoluteFillObject,
        opacity: 0.16,
        backgroundColor: 'transparent',
    },
    scrollContent: {
        paddingHorizontal: allergiesDashboardSpacing.xl,
        paddingBottom: allergiesDashboardSpacing.xxxl,
        gap: allergiesDashboardSpacing.lg,
    },
    sectionCard: {
        borderRadius: allergiesDashboardRadii.lg,
        borderCurve: 'continuous',
        borderWidth: 1,
        borderColor: allergiesDashboardColors.line,
        backgroundColor: allergiesDashboardColors.surface,
        padding: allergiesDashboardSpacing.md,
        gap: allergiesDashboardSpacing.sm,
        boxShadow: allergiesDashboardShadows.card,
    },
    elevatedCard: {
        borderRadius: allergiesDashboardRadii.xl,
        borderCurve: 'continuous',
        borderWidth: 1,
        borderColor: allergiesDashboardColors.line,
        backgroundColor: allergiesDashboardColors.surfaceStrong,
        padding: allergiesDashboardSpacing.lg,
        gap: allergiesDashboardSpacing.md,
        boxShadow: allergiesDashboardShadows.hero,
    },
    railHeader: {
        gap: allergiesDashboardSpacing.xs,
    },
    railEyebrow: {
        fontSize: allergiesDashboardTypography.caption,
        lineHeight: 16,
        fontWeight: '800',
        letterSpacing: 0.8,
        textTransform: 'uppercase',
        color: allergiesDashboardColors.inkSoft,
    },
    railTitle: {
        fontSize: allergiesDashboardTypography.section,
        lineHeight: 28,
        fontWeight: '800',
        letterSpacing: -0.5,
        color: allergiesDashboardColors.ink,
    },
    railDescription: {
        fontSize: allergiesDashboardTypography.body,
        lineHeight: 21,
        color: allergiesDashboardColors.inkSoft,
    },
    railMetaRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: allergiesDashboardSpacing.xs,
        marginTop: allergiesDashboardSpacing.xs,
    },
    pill: {
        minHeight: 30,
        paddingHorizontal: allergiesDashboardSpacing.sm,
        borderRadius: allergiesDashboardRadii.pill,
        borderCurve: 'continuous',
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: allergiesDashboardColors.line,
        backgroundColor: allergiesDashboardColors.surfaceMuted,
    },
    pillText: {
        fontSize: allergiesDashboardTypography.caption,
        lineHeight: 14,
        fontWeight: '800',
        letterSpacing: 0.6,
        textTransform: 'uppercase',
        color: allergiesDashboardColors.inkSoft,
    },
    heroCopy: {
        gap: allergiesDashboardSpacing.xs,
    },
    heroEyebrow: {
        fontSize: allergiesDashboardTypography.caption,
        lineHeight: 16,
        fontWeight: '800',
        letterSpacing: 0.8,
        textTransform: 'uppercase',
        color: allergiesDashboardColors.inkSoft,
    },
    heroTitle: {
        fontSize: 28,
        lineHeight: 34,
        fontWeight: '900',
        letterSpacing: -0.8,
        color: allergiesDashboardColors.ink,
    },
    heroDescription: {
        fontSize: allergiesDashboardTypography.body,
        lineHeight: 22,
        color: allergiesDashboardColors.inkSoft,
    },
    heroMetaRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: allergiesDashboardSpacing.xs,
    },
    heroActionRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: allergiesDashboardSpacing.sm,
        alignItems: 'center',
    },
    primaryActionButton: {
        minHeight: 46,
        paddingHorizontal: allergiesDashboardSpacing.lg,
        borderRadius: allergiesDashboardRadii.pill,
        borderCurve: 'continuous',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: allergiesDashboardColors.ink,
        borderWidth: 1,
        borderColor: allergiesDashboardColors.ink,
    },
    primaryActionButtonText: {
        fontSize: allergiesDashboardTypography.bodyStrong,
        lineHeight: 18,
        fontWeight: '800',
        letterSpacing: -0.2,
        color: allergiesDashboardColors.paper,
    },
    secondaryActionButton: {
        minHeight: 46,
        paddingHorizontal: allergiesDashboardSpacing.lg,
        borderRadius: allergiesDashboardRadii.pill,
        borderCurve: 'continuous',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: allergiesDashboardColors.surfaceMuted,
        borderWidth: 1,
        borderColor: allergiesDashboardColors.lineStrong,
    },
    secondaryActionButtonText: {
        fontSize: allergiesDashboardTypography.bodyStrong,
        lineHeight: 18,
        fontWeight: '800',
        letterSpacing: -0.2,
        color: allergiesDashboardColors.ink,
    },
    emptyBadge: {
        alignSelf: 'flex-start',
        minHeight: 30,
        paddingHorizontal: allergiesDashboardSpacing.sm,
        borderRadius: allergiesDashboardRadii.pill,
        borderCurve: 'continuous',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: allergiesDashboardColors.pearlMist,
        borderWidth: 1,
        borderColor: allergiesDashboardColors.line,
    },
    emptyBadgeText: {
        fontSize: allergiesDashboardTypography.caption,
        lineHeight: 14,
        fontWeight: '800',
        letterSpacing: 0.6,
        textTransform: 'uppercase',
        color: allergiesDashboardColors.accentBlue,
    },
    emptyTitle: {
        fontSize: 26,
        lineHeight: 32,
        fontWeight: '900',
        letterSpacing: -0.6,
        color: allergiesDashboardColors.ink,
    },
    emptyDescription: {
        fontSize: allergiesDashboardTypography.body,
        lineHeight: 22,
        color: allergiesDashboardColors.inkSoft,
    },
    emptyActionRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: allergiesDashboardSpacing.sm,
    },
    modalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(15, 23, 42, 0.82)',
    },
    modalSafeArea: {
        flex: 1,
        justifyContent: 'center',
        paddingHorizontal: allergiesDashboardSpacing.lg,
        paddingBottom: allergiesDashboardSpacing.xl,
    },
    modalSheet: {
        borderRadius: allergiesDashboardRadii.xl,
        borderCurve: 'continuous',
        borderWidth: 1,
        borderColor: 'rgba(255, 255, 255, 0.12)',
        backgroundColor: allergiesDashboardColors.surfaceStrong,
        overflow: 'hidden',
        boxShadow: allergiesDashboardShadows.hero,
    },
    modalHeader: {
        alignItems: 'center',
        borderBottomWidth: 1,
        borderColor: allergiesDashboardColors.line,
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: allergiesDashboardSpacing.lg,
        paddingTop: allergiesDashboardSpacing.lg,
        paddingBottom: allergiesDashboardSpacing.sm,
    },
    modalTitle: {
        color: allergiesDashboardColors.ink,
        fontSize: allergiesDashboardTypography.bodyStrong,
        fontWeight: '800',
        lineHeight: 18,
    },
    modalCloseButton: {
        alignItems: 'center',
        backgroundColor: allergiesDashboardColors.surfaceMuted,
        borderColor: allergiesDashboardColors.lineStrong,
        borderCurve: 'continuous',
        borderRadius: allergiesDashboardRadii.pill,
        borderWidth: 1,
        height: 38,
        justifyContent: 'center',
        width: 38,
    },
    modalContent: {
        padding: allergiesDashboardSpacing.lg,
    },
    modalBodyFrame: {
        borderRadius: allergiesDashboardRadii.lg,
        borderCurve: 'continuous',
        borderWidth: 1,
        borderColor: allergiesDashboardColors.line,
        backgroundColor: allergiesDashboardColors.surface,
        padding: allergiesDashboardSpacing.md,
        boxShadow: allergiesDashboardShadows.card,
    },
});
