import { StyleSheet, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');
const VIEWFINDER_SIZE = 280;
const verticalMargin = (SCREEN_HEIGHT - VIEWFINDER_SIZE) / 2;
const horizontalMargin = (SCREEN_WIDTH - VIEWFINDER_SIZE) / 2;

export const scanCameraStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'black',
    },
    permissionContainer: {
        flex: 1,
        backgroundColor: '#000',
        justifyContent: 'center',
        alignItems: 'center',
    },
    permissionText: {
        color: 'white',
        fontSize: 16,
        marginBottom: 20,
    },
    permissionButton: {
        backgroundColor: '#2563EB',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
    },
    permissionButtonText: {
        color: 'white',
        fontWeight: 'bold',
    },
    closeButton: {
        position: 'absolute',
        top: 60,
        right: 20,
        padding: 10,
    },
    topBar: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 10,
        zIndex: 10,
    },
    topCenterControls: {
        flexDirection: 'row',
        gap: 20,
    },
    iconButton: {
        width: 44,
        height: 44,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 22,
        backgroundColor: 'rgba(0,0,0,0.3)',
    },
    overlay: {
        ...StyleSheet.absoluteFillObject,
        justifyContent: 'center',
        alignItems: 'center',
    },
    viewfinderContainer: {
        width: 280,
        height: 280,
        position: 'relative',
    },
    corner: {
        position: 'absolute',
        width: 30,
        height: 30,
        borderColor: 'white',
        borderWidth: 4,
    },
    tl: { top: 0, left: 0, borderRightWidth: 0, borderBottomWidth: 0, borderTopLeftRadius: 20 },
    tr: { top: 0, right: 0, borderLeftWidth: 0, borderBottomWidth: 0, borderTopRightRadius: 20 },
    bl: { bottom: 0, left: 0, borderRightWidth: 0, borderTopWidth: 0, borderBottomLeftRadius: 20 },
    br: { bottom: 0, right: 0, borderLeftWidth: 0, borderTopWidth: 0, borderBottomRightRadius: 20 },
    laserContainer: {
        position: 'absolute',
        left: 0,
        right: 0,
        height: 40,
        justifyContent: 'center',
        alignItems: 'center',
        zIndex: 20,
    },
    premiumLaser: {
        width: '100%',
        height: 3,
        shadowColor: '#FF3B30',
        shadowOffset: { width: 0, height: 0 },
        shadowOpacity: 1,
        shadowRadius: 8,
        elevation: 5,
    },
    blurTop: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        height: verticalMargin,
    },
    blurBottom: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        height: verticalMargin,
    },
    blurLeft: {
        position: 'absolute',
        top: verticalMargin,
        bottom: verticalMargin,
        left: 0,
        width: horizontalMargin,
    },
    blurRight: {
        position: 'absolute',
        top: verticalMargin,
        bottom: verticalMargin,
        right: 0,
        width: horizontalMargin,
    },
    bottomBar: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingBottom: 40,
        paddingTop: 40,
        alignItems: 'center',
        gap: 20,
    },
    contextControls: {
        flexDirection: 'row',
        gap: 40,
        marginBottom: 10,
    },
    zoomButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(50,50,50,0.8)',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        gap: 4,
    },
    zoomText: {
        color: 'white',
        fontWeight: '600',
        fontSize: 14,
    },
    searchButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: 'rgba(50,50,50,0.8)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    shutterRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        width: '100%',
        paddingHorizontal: 40,
    },
    galleryButton: {
        width: 50,
        height: 50,
        borderRadius: 25,
        backgroundColor: '#333',
        justifyContent: 'center',
        alignItems: 'center',
    },
    shutterButton: {
        width: 80,
        height: 80,
        borderRadius: 40,
        borderWidth: 5,
        borderColor: 'white',
        padding: 4,
        justifyContent: 'center',
        alignItems: 'center',
    },
    shutterInner: {
        width: '100%',
        height: '100%',
        backgroundColor: 'white',
        borderRadius: 40,
    },
    shutterInnerBarcode: {
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: 'white',
    },
    modeSelector: {
        flexDirection: 'row',
        backgroundColor: 'rgba(0,0,0,0.5)',
        borderRadius: 30,
        padding: 4,
        gap: 4,
    },
    modeChip: {
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 20,
    },
    modeChipActive: {
        backgroundColor: '#3F3F46',
    },
    modeText: {
        color: '#71717A',
        fontWeight: '600',
        fontSize: 14,
    },
    modeTextActive: {
        color: 'white',
    },
    guideText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
        marginTop: 20,
        textShadowColor: 'rgba(0, 0, 0, 0.75)',
        textShadowOffset: { width: 0, height: 1 },
        textShadowRadius: 3,
    },
});
