import { Platform, StyleSheet } from 'react-native';

export const onboardingStyles = StyleSheet.create({
  safeArea: { flex: 1 },
  progressContainer: {
    flexDirection: 'row',
    paddingHorizontal: 24,
    paddingTop: 12,
    gap: 6,
  },
  progressDot: {
    height: 4,
    borderRadius: 2,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 8,
    marginTop: 4,
  },
  backText: {
    fontSize: 16,
    fontWeight: '500',
    marginLeft: 2,
  },
  stepContainer: {
    flex: 1,
    paddingHorizontal: 24,
    justifyContent: 'center',
  },
  stepScroll: {
    flex: 1,
  },
  stepScrollContent: {
    paddingHorizontal: 24,
    paddingTop: 8,
  },
  destinationStepContent: {
    flexGrow: 1,
    justifyContent: 'space-between',
    gap: 24,
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  permissionsStepContent: {
    flexGrow: 1,
    justifyContent: 'space-between',
    gap: 18,
    paddingHorizontal: 24,
    paddingTop: 4,
    paddingBottom: 24,
  },
  heroArea: {
    alignItems: 'center',
    marginBottom: 32,
  },
  heroAreaScroll: {
    alignItems: 'center',
    marginBottom: 32,
    paddingTop: 12,
  },
  welcomeEmoji: {
    fontSize: 64,
    marginBottom: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 12,
  },
  subtitle: {
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
    paddingHorizontal: 8,
  },
  heroImageWrapper: {
    width: '100%',
    aspectRatio: 1,
    maxWidth: 300,
    alignSelf: 'center',
    position: 'relative',
  },
  heroImagePlaceholder: {
    width: '100%',
    height: '100%',
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  floatingBadge: {
    position: 'absolute',
    padding: 10,
    borderRadius: 16,
    borderWidth: 1,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 12,
    elevation: 8,
  },
  floatingBadgeRight: {
    top: 30,
    right: -8,
  },
  floatingBadgeLeft: {
    bottom: 60,
    left: -8,
  },
  welcomeTitle: {
    fontSize: 34,
    fontWeight: '800',
    textAlign: 'center',
    letterSpacing: 0,
    marginTop: 16,
  },
  welcomeSubtitle: {
    fontSize: 17,
    fontWeight: '500',
    textAlign: 'center',
    paddingHorizontal: 28,
    marginTop: 6,
    marginBottom: 4,
  },
  safetyBrandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 18,
  },
  safetyBrandMark: {
    width: 38,
    height: 38,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  safetyBrandMarkText: {
    color: '#FFFFFF',
    fontWeight: '900',
    fontSize: 13,
  },
  safetyBrandName: {
    fontSize: 18,
    fontWeight: '800',
  },
  kickerText: {
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    textAlign: 'center',
    marginBottom: 10,
  },
  resultPreviewCard: {
    borderRadius: 26,
    borderWidth: 1,
    overflow: 'hidden',
    minHeight: 330,
    marginBottom: 24,
  },
  resultPreviewImage: {
    width: '100%',
    height: 330,
  },
  resultPreviewOverlay: {
    position: 'absolute',
    left: 16,
    right: 16,
    top: 16,
    bottom: 16,
    justifyContent: 'space-between',
  },
  resultPreviewBadge: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(15, 23, 42, 0.72)',
  },
  resultPreviewBadgeText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '800',
  },
  analysisPreviewPanel: {
    borderRadius: 22,
    padding: 14,
    borderWidth: 1,
    gap: 12,
  },
  analysisPreviewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  analysisPreviewFood: {
    fontSize: 18,
    fontWeight: '800',
  },
  analysisPreviewRisk: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(254, 226, 226, 0.96)',
  },
  analysisPreviewRiskText: {
    color: '#DC2626',
    fontSize: 12,
    fontWeight: '800',
  },
  analysisPreviewGrid: {
    flexDirection: 'row',
    gap: 10,
  },
  analysisPreviewCell: {
    flex: 1,
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
  },
  analysisPreviewCellTitle: {
    fontSize: 14,
    fontWeight: '800',
  },
  analysisPreviewCellSub: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: 4,
  },
  bentoGrid: {
    marginTop: 20,
    gap: 10,
  },
  bentoCardFull: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
    gap: 14,
  },
  bentoHalfRow: {
    flexDirection: 'row',
    gap: 10,
  },
  bentoCardHalf: {
    flex: 1,
    padding: 16,
    borderRadius: 20,
    borderWidth: 1,
  },
  bentoIconCircle: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bentoCardTitle: {
    fontSize: 15,
    fontWeight: '700',
  },
  bentoCardSub: {
    fontSize: 12,
    marginTop: 2,
  },
  paginationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginTop: 20,
    marginBottom: 20,
  },
  paginationDot: {
    height: 8,
    borderRadius: 4,
  },
  primaryButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 18,
    borderRadius: 9999,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  primaryButtonText: {
    color: 'white',
    fontSize: 18,
    fontWeight: 'bold',
  },
  skipButton: {
    alignItems: 'center',
    marginTop: 16,
    padding: 8,
  },
  skipText: {
    fontSize: 15,
    fontWeight: '500',
  },
  permissionCard: {
    borderRadius: 20,
    padding: 20,
    marginBottom: 32,
    gap: 20,
  },
  permissionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 16,
  },
  permissionIcon: {
    width: 52,
    height: 52,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  permissionTitle: {
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 2,
  },
  permissionDesc: {
    fontSize: 14,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 4,
  },
  severityHint: {
    fontSize: 13,
    marginBottom: 12,
  },
  severityRow: {
    alignItems: 'stretch',
    padding: 14,
    borderRadius: 14,
    marginBottom: 8,
    borderWidth: 1,
    gap: 12,
  },
  severityAllergenName: {
    fontSize: 16,
    fontWeight: '600',
  },
  severityBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    gap: 4,
  },
  severityBadgeText: {
    fontSize: 13,
    fontWeight: '700',
  },
  severitySegmentRow: {
    flexDirection: 'row',
    gap: 6,
  },
  severitySegment: {
    flex: 1,
    minHeight: 38,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    paddingHorizontal: 4,
  },
  priorityCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
  },
  priorityIcon: {
    width: 42,
    height: 42,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
  },
  priorityIconText: {
    fontSize: 18,
    fontWeight: '900',
  },
  priorityTitle: {
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 3,
  },
  priorityDesc: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '500',
  },
  destinationMapCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 16,
    borderRadius: 18,
    borderWidth: 1,
    marginTop: 20,
  },
  destinationMapTitle: {
    fontSize: 15,
    fontWeight: '800',
  },
  destinationMapSub: {
    fontSize: 12,
    lineHeight: 17,
    marginTop: 3,
  },
  destinationRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    padding: 14,
    borderRadius: 16,
    borderWidth: 1,
  },
  destinationFlag: {
    width: 42,
    height: 42,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  destinationFlagText: {
    fontSize: 13,
    fontWeight: '900',
  },
  destinationTitle: {
    fontSize: 16,
    fontWeight: '800',
  },
  destinationSub: {
    fontSize: 13,
    marginTop: 2,
  },
  secondaryActionButton: {
    minHeight: 52,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  secondaryActionText: {
    fontSize: 15,
    fontWeight: '800',
  },
  secondaryActionMeta: {
    marginLeft: 'auto',
    fontSize: 12,
    fontWeight: '700',
  },
  passportCard: {
    borderRadius: 24,
    borderWidth: 1,
    padding: 18,
    marginTop: 22,
  },
  passportHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginBottom: 16,
  },
  passportHeaderTitle: {
    fontSize: 15,
    fontWeight: '800',
  },
  passportLanguageBadge: {
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  passportLanguageText: {
    fontSize: 12,
    fontWeight: '800',
  },
  passportMessage: {
    fontSize: 17,
    fontWeight: '700',
    lineHeight: 25,
  },
  passportTags: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 16,
  },
  passportTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    maxWidth: '100%',
    borderWidth: 1,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  passportTagText: {
    fontSize: 12,
    fontWeight: '800',
  },
  passportEmptyText: {
    marginTop: 16,
    fontSize: 13,
    lineHeight: 19,
  },
  restaurantModeCard: {
    borderRadius: 16,
    borderWidth: 1,
    padding: 14,
    marginTop: 14,
  },
  restaurantModeKicker: {
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  restaurantModeText: {
    fontSize: 13,
    lineHeight: 19,
  },
  permissionPreviewCard: {
    borderRadius: 24,
    borderWidth: 1,
    overflow: 'hidden',
    marginTop: 18,
  },
  permissionPreviewImage: {
    width: '100%',
    height: 188,
  },
  scanCoachmark: {
    borderTopWidth: 1,
    padding: 14,
  },
  scanCoachmarkTitle: {
    fontSize: 16,
    fontWeight: '800',
    marginBottom: 6,
  },
  scanCoachmarkText: {
    fontSize: 13,
    lineHeight: 19,
  },
  privacyCard: {
    marginTop: 12,
    borderRadius: 16,
    borderWidth: 1,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
  },
  privacyCardText: {
    flex: 1,
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '500',
  },
  readyHero: {
    alignItems: 'center',
    marginBottom: 18,
  },
  readyStamp: {
    width: 116,
    height: 116,
    borderRadius: 58,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  readyStampText: {
    color: '#FFFFFF',
    fontSize: 12,
    fontWeight: '900',
    textTransform: 'uppercase',
    textAlign: 'center',
  },
  readyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  readyIcon: {
    width: 40,
    height: 40,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  readyTitle: {
    fontSize: 15,
    fontWeight: '800',
  },
  readySub: {
    fontSize: 13,
    lineHeight: 18,
    marginTop: 3,
  },
  readyStatusOn: {
    color: '#059669',
    fontSize: 12,
    fontWeight: '900',
  },
  readyStatusReady: {
    color: '#2563EB',
    fontSize: 12,
    fontWeight: '900',
  },
  readyPermissionNote: {
    fontSize: 13,
    lineHeight: 19,
    textAlign: 'center',
    marginTop: 16,
    paddingHorizontal: 8,
  },
  tagContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  tag: {
    borderRadius: 100,
    paddingHorizontal: 16,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
  },
  tagText: {
    fontWeight: '600',
    fontSize: 14,
  },
  summaryCard: {
    borderRadius: 20,
    padding: 20,
    marginBottom: 32,
  },
  summaryTitle: {
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 12,
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: '#eee',
  },
  summaryAllergen: {
    fontSize: 16,
    fontWeight: '500',
  },
  footerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderTopWidth: 1,
    paddingBottom: Platform.OS === 'ios' ? 4 : 12,
  },
  genderGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  genderCard: {
    width: '47%',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 16,
    borderWidth: 1,
    gap: 10,
  },
  genderIcon: {
    fontSize: 24,
  },
  genderLabel: {
    fontSize: 15,
    fontWeight: '600',
  },
  pickerWrapper: {
    borderRadius: 16,
    borderWidth: 1,
    overflow: 'hidden',
    marginTop: 8,
  },
  pickerAge: {
    fontSize: 14,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 8,
  },
  yearPickerBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 24,
  },
  yearPickerDismissArea: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
  },
  yearPickerSheet: {
    width: '100%',
    maxWidth: 360,
    maxHeight: 460,
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 14,
  },
  yearPickerTitle: {
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 10,
  },
  yearPickerCloseButton: {
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    marginTop: 14,
  },
  yearPickerCloseButtonText: {
    color: '#ffffff',
    fontSize: 15,
    fontWeight: '700',
  },
  birthWheelRow: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'flex-start',
    marginTop: 4,
  },
  birthWheelColumn: {
    flex: 1,
    alignItems: 'center',
  },
  birthWheelLabel: {
    fontSize: 12,
    fontWeight: '600',
    marginBottom: 8,
  },
  birthWheelViewport: {
    height: 220,
    borderRadius: 14,
    borderWidth: 1,
    overflow: 'hidden',
    width: '100%',
    position: 'relative',
  },
  birthWheelScroll: {
    flex: 1,
  },
  birthWheelContent: {
    paddingVertical: 88,
  },
  birthWheelItem: {
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
  },
  birthWheelItemText: {
    fontSize: 18,
    fontWeight: '500',
    opacity: 0.55,
  },
  birthWheelItemTextSelected: {
    fontWeight: '800',
    opacity: 1,
  },
  birthWheelSelectedOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 88,
    height: 44,
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    backgroundColor: 'rgba(148, 163, 184, 0.08)',
  },
  birthWheelValuePreview: {
    marginTop: 8,
    fontSize: 13,
    fontWeight: '600',
    opacity: 0.85,
  },
});
