import { StyleSheet } from 'react-native';

export const homeStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  offlineBanner: {
    backgroundColor: '#EF4444',
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  offlineText: {
    color: 'white',
    fontSize: 12,
    fontWeight: 'bold',
  },
  backgroundContainer: {
    ...StyleSheet.absoluteFillObject,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    marginTop: 2,
  },
  userInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  avatarContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: '#DBEAFE',
    borderWidth: 2,
    borderColor: 'white',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  avatar: {
    width: 48,
    height: 48,
  },
  welcomeText: {
    fontSize: 12,
    color: '#64748B',
    fontWeight: '500',
  },
  userName: {
    fontSize: 18,
    color: '#0F172A',
    fontWeight: '700',
  },
  topfoldSection: {
    gap: 16,
    marginBottom: 18,
  },
  signalCard: {
    position: 'relative',
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 28,
    elevation: 3,
  },
  statusGlow: {
    position: 'absolute',
    top: -34,
    right: -34,
    width: 164,
    height: 164,
    borderRadius: 999,
  },
  signalHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  statusKicker: {
    alignSelf: 'flex-start',
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: '#FCE7F3',
  },
  statusKickerCalm: {
    backgroundColor: '#DCFCE7',
  },
  statusKickerText: {
    fontSize: 12,
    fontWeight: '800',
    color: '#E11D63',
  },
  statusKickerTextCalm: {
    color: '#166534',
  },
  signalDateLabel: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    color: '#94A3B8',
  },
  signalHeadline: {
    fontSize: 34,
    lineHeight: 36,
    fontWeight: '900',
    letterSpacing: -1.2,
    color: '#0F172A',
  },
  signalSubline: {
    marginTop: 8,
    fontSize: 14,
    lineHeight: 19,
    fontWeight: '600',
    color: '#64748B',
  },
  metricPillStack: {
    gap: 10,
    marginTop: 14,
  },
  metricPill: {
    minHeight: 58,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  metricPillPressed: {
    opacity: 0.82,
  },
  metricPillActive: {
    transform: [{ scale: 0.985 }],
  },
  metricPillMain: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  metricPillSafe: {
    backgroundColor: '#86EFAC',
  },
  metricPillCaution: {
    backgroundColor: '#FEF3C7',
  },
  metricPillDanger: {
    backgroundColor: '#F1F5F9',
  },
  metricPillIconSafe: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.44)',
  },
  metricPillIconCaution: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.5)',
  },
  metricPillIconDanger: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  metricPillValue: {
    fontSize: 22,
    lineHeight: 24,
    fontWeight: '900',
    letterSpacing: -0.6,
    color: '#0F172A',
  },
  metricPillSafeText: {
    color: '#14532D',
  },
  metricPillCautionText: {
    color: '#92400E',
  },
  metricPillDangerText: {
    color: '#64748B',
  },
  statusSignalChip: {
    alignSelf: 'flex-start',
    marginTop: 16,
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 999,
  },
  statusSignalChipText: {
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '900',
  },
  featuredScanCard: {
    borderRadius: 28,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#E2E8F0',
    backgroundColor: '#FFFFFF',
  },
  featuredScanMedia: {
    position: 'relative',
    height: 224,
  },
  featuredScanThumbnail: {
    width: '100%',
    height: '100%',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    backgroundColor: '#E2E8F0',
  },
  featuredScanThumbnailImage: {
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
  },
  featuredScanBadge: {
    position: 'absolute',
    top: 16,
    left: 16,
    minHeight: 32,
    paddingHorizontal: 12,
    borderRadius: 999,
    justifyContent: 'center',
  },
  featuredScanBadgeText: {
    fontSize: 12,
    lineHeight: 14,
    fontWeight: '900',
  },
  featuredScanBody: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 16,
    padding: 18,
  },
  featuredScanCopy: {
    flex: 1,
  },
  featuredScanEyebrow: {
    fontSize: 11,
    lineHeight: 14,
    fontWeight: '800',
    color: '#94A3B8',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  featuredScanName: {
    marginTop: 4,
    fontSize: 24,
    lineHeight: 26,
    fontWeight: '900',
    letterSpacing: -0.8,
    color: '#0F172A',
  },
  featuredScanMeta: {
    marginTop: 6,
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    color: '#94A3B8',
  },
  featuredScanAction: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F8FAFC',
    borderWidth: 1,
    borderColor: '#E2E8F0',
  },
  cautionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: 'rgba(251, 191, 36, 0.3)',
    backgroundColor: '#FFF7ED',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  cautionRowCalm: {
    borderColor: 'rgba(34, 197, 94, 0.2)',
    backgroundColor: '#F0FDF4',
  },
  cautionIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: 'rgba(255,255,255,0.8)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cautionIconWrapCalm: {
    backgroundColor: 'rgba(255,255,255,0.72)',
  },
  cautionCopy: {
    flex: 1,
  },
  cautionTitle: {
    fontSize: 13,
    lineHeight: 17,
    fontWeight: '900',
    color: '#9A3412',
  },
  cautionTitleCalm: {
    color: '#166534',
  },
  cautionDescription: {
    marginTop: 2,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '500',
    color: '#64748B',
  },
  summaryBadge: {
    minWidth: 38,
    height: 26,
    paddingHorizontal: 10,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(225, 29, 99, 0.12)',
  },
  summaryBadgeCalm: {
    backgroundColor: 'rgba(22, 101, 52, 0.12)',
  },
  summaryBadgeText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#E11D63',
  },
  summaryBadgeTextCalm: {
    color: '#166534',
  },
  weeklyContainer: {
    marginBottom: 12,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
    gap: 12,
  },
  sectionHeaderCopy: {
    flex: 1,
  },
  sectionTitle: {
    fontSize: 16,
    lineHeight: 20,
    fontWeight: '800',
    color: '#1E293B',
  },
  sectionCaption: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 17,
    fontWeight: '500',
    color: '#64748B',
  },
  seeAllText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '600',
    color: '#94A3B8',
  },
  scanList: {
    gap: 12,
    marginBottom: 12,
  },
  scanItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.72)',
    borderColor: '#E2E8F0',
    borderWidth: 1,
    padding: 14,
    borderRadius: 22,
  },
  scanInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
    flexShrink: 1,
  },
  scanEmojiBox: {
    width: 44,
    height: 44,
    backgroundColor: 'white',
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.03,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  scanName: {
    fontSize: 15,
    fontWeight: '800',
    color: '#1E293B',
    maxWidth: 180,
  },
  scanDate: {
    fontSize: 12,
    color: '#94A3B8',
    marginTop: 2,
  },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 100,
    marginLeft: 10,
  },
  badgeText: {
    fontSize: 10,
    fontWeight: '900',
  },
  deleteAction: {
    backgroundColor: '#EF4444',
    justifyContent: 'center',
    alignItems: 'flex-end',
    width: 80,
    height: '100%',
    borderRadius: 24,
  },
  deleteBtnContent: {
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 80,
    height: '100%',
  },
  deleteText: {
    color: 'white',
    fontSize: 10,
    fontWeight: 'bold',
    marginTop: 4,
  },
});
