import { StyleSheet } from 'react-native';

export const historyMapStyles = StyleSheet.create({
    mapContainer: { flex: 1, overflow: 'hidden', marginHorizontal: 20, marginBottom: 20, borderRadius: 32, borderWidth: 1, borderColor: '#E2E8F0', backgroundColor: '#F1F5F9' },
    map: { width: '100%', height: '100%' },
    errorOverlay: { backgroundColor: '#F1F5F9', alignItems: 'center', justifyContent: 'center', zIndex: 20 },
    errorContent: { alignItems: 'center', opacity: 0.7, paddingHorizontal: 40 },
    errorTitle: { marginTop: 12, color: '#64748B', fontWeight: '600', textAlign: 'center' },
    errorDescription: { marginTop: 8, color: '#94A3B8', fontSize: 12, textAlign: 'center' },
    errorButton: { marginTop: 16, borderRadius: 20 },
    settingsButton: { paddingHorizontal: 20, paddingVertical: 10, backgroundColor: '#2563EB' },
    settingsButtonText: { fontSize: 13, fontWeight: '700', color: '#FFFFFF' },
    retryButton: { paddingHorizontal: 16, paddingVertical: 8, backgroundColor: '#E2E8F0' },
    retryButtonText: { fontSize: 12, fontWeight: '700', color: '#475569' },
    loadingOverlay: { backgroundColor: '#E2E8F0', alignItems: 'center', justifyContent: 'center', zIndex: 10 },
    loadingEmoji: { fontSize: 24, marginBottom: 12 },
    loadingText: { color: '#64748B', fontSize: 12, fontWeight: '600' },
    mapPinContainer: { alignItems: 'center' },
    mapLabel: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: 12, overflow: 'hidden', marginBottom: 4, backgroundColor: 'rgba(255,255,255,0.85)' },
    mapLabelText: { fontSize: 10, fontWeight: '700', color: '#1E293B', maxWidth: 100 },
    mapPinCircle: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', borderWidth: 2, borderColor: '#FFFFFF', shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 3, elevation: 3 },
    mapPinEmoji: { fontSize: 16 },
    clusterContainer: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' },
    clusterCircle: { width: 40, height: 40, borderRadius: 20, borderWidth: 2, borderColor: '#FFFFFF', backgroundColor: '#EFF6FF', alignItems: 'center', justifyContent: 'center' },
    clusterEmoji: { fontSize: 18 },
    clusterBadge: { position: 'absolute', top: -4, right: -4, backgroundColor: '#2563EB', borderRadius: 10, width: 20, height: 20, alignItems: 'center', justifyContent: 'center', borderWidth: 1.5, borderColor: 'white' },
    clusterCountText: { color: 'white', fontSize: 10, fontWeight: '700' },
    mapOverlay: { position: 'absolute', bottom: 20, left: 20, right: 20, borderRadius: 32 },
    insightCard: { padding: 20, borderRadius: 32, overflow: 'hidden' },
    insightCardBg: { backgroundColor: 'rgba(255,255,255,0.92)' },
    insightHeader: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 16 },
    insightIconBox: { width: 32, height: 32, borderRadius: 16, backgroundColor: '#EFF6FF', alignItems: 'center', justifyContent: 'center' },
    insightTitle: { fontSize: 14, fontWeight: '700', color: '#1E293B' },
    insightRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
    insightLabel: { fontSize: 13, color: '#64748B', fontWeight: '500' },
    insightValue: { fontSize: 14, fontWeight: '700', color: '#0F172A' },
    progressBarBg: { height: 6, backgroundColor: '#F1F5F9', borderRadius: 3, marginBottom: 12, overflow: 'hidden' },
    progressBarFill: { height: '100%', backgroundColor: '#2563EB', borderRadius: 3 },
    insightHint: { fontSize: 11, color: '#94A3B8', textAlign: 'center', marginTop: 4 },
    toastContainer: { position: 'absolute', top: 20, left: 0, right: 0, alignItems: 'center', zIndex: 100 },
    toast: { paddingHorizontal: 16, paddingVertical: 10, borderRadius: 20, overflow: 'hidden' },
    toastBg: { backgroundColor: 'rgba(0,0,0,0.75)' },
    toastText: { color: '#FFFFFF', fontSize: 13, fontWeight: '600' },
});
