import React, { useState, useEffect } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { Sparkles, MapPin, Globe } from 'lucide-react-native';
import { ALLERGY_TRANSLATIONS, ALLERGEN_TERMS } from '../services/staticTranslations';
import { UserService } from '../services/userService';

interface TravelerAllergyCardProps {
  countryCode: string | null;
  aiTranslation: {
      language: string;
      text: string | null;
      audio_query?: string;
  } | undefined | null;
}

export default function TravelerAllergyCard({ countryCode, aiTranslation }: TravelerAllergyCardProps) {
  const [userAllergens, setUserAllergens] = useState<string[]>([]);

  useEffect(() => {
    UserService.getUserProfile("test-user-v1").then(p => {
        if (p) setUserAllergens([...p.safetyProfile.allergies, ...p.safetyProfile.dietaryRestrictions]);
    }).catch(e => console.warn(e));
  }, []);

  // If not in a foreign country (or country unknown) AND no AI translation, hide.
  // Actually, we want to show it if countryCode is known, even if AI is loading.
  if (!countryCode && !aiTranslation) return null;
  
  // Use 'US' or 'DEFAULT' if countryCode is null
  const code = countryCode || 'DEFAULT';
  const staticData = ALLERGY_TRANSLATIONS[code] || ALLERGY_TRANSLATIONS['DEFAULT'];
  
  // Logic: 
  // If AI provided text, use it (Dynamic Mode).
  // If not, use Static text (Safety/Offline Mode) - ONLY TO BE SHOWN if we are reasonably sure user needs it?
  // But user request says "Show it".
  
  // If AI loaded and specifically said text is null (meaning no allergies), we still might show static card?
  // No, if AI says "No allergies", we should respect that.
  
  const isAiLoaded = aiTranslation !== undefined;
  
  if (isAiLoaded && aiTranslation === null) {
       // AI analysis done, but no translation card generated (e.g. no allergies)
       return null;
  }
  
  if (isAiLoaded && aiTranslation && aiTranslation.text === null) {
      // AI explicit null text
      return null;
  }
  
  const displayData = (isAiLoaded && aiTranslation) ? {
      language: aiTranslation.language,
      text: aiTranslation.text || staticData.text, // Fallback if AI text empty but obj exists
      sub: "Auto-generated by AI Health Coach"
  } : {
      language: staticData.language,
      text: staticData.text,
      sub: "Traveler Safety Card (GPS Linked)"
  };

  // If Static Mode (no AI result), append specific allergens from profile
  let finalMessage = displayData.text;
  if (!aiTranslation && userAllergens.length > 0) {
      // Translate allergens to local language if possible
      const targetCode = countryCode || 'US';
      const translatedList = userAllergens.map(allergen => {
          // Normalize: Handle "PEANUTS", "peanuts", "Peanuts"
          const lower = allergen.trim().toLowerCase();
          const titleCase = lower.charAt(0).toUpperCase() + lower.slice(1);
          
          // Try exact match first, then normalized Title Case
          const dict = ALLERGEN_TERMS[allergen] || ALLERGEN_TERMS[titleCase];
          
          if (dict) {
              return dict[targetCode] || allergen; // Fallback to English if language not found
          }
          return allergen; // Fallback to English if allergen not in dictionary
      });
      
      finalMessage += `\n\n⚠️ My Allergies:\n${translatedList.join(", ")}`;
  }

  return (
    <View style={styles.container}>
      <View style={styles.header}>
          <Globe size={16} color="#3B82F6" />
          <Text style={styles.headerTitle}>TRAVELER ALLERGY CARD • {displayData.language.toUpperCase()}</Text>
          {isAiLoaded && <Sparkles size={14} color="#F59E0B" />}
      </View>
      
      <View style={styles.card}>
          <Text style={styles.mainText}>{finalMessage}</Text>
          <View style={styles.footer}>
            <Text style={styles.subText}>{displayData.sub}</Text>
          </View>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
    container: {
        marginBottom: 24,
        paddingHorizontal: 0, 
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginBottom: 12,
        paddingHorizontal: 8,
    },
    headerTitle: {
        fontSize: 12,
        fontWeight: '800',
        color: '#64748B',
        letterSpacing: 1,
    },
    card: {
        backgroundColor: '#EFF6FF',
        borderRadius: 24,
        padding: 24,
        borderWidth: 1,
        borderColor: '#BFDBFE',
        shadowColor: '#3B82F6',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    mainText: {
        fontSize: 22,
        fontWeight: '700',
        color: '#1E3A8A',
        marginBottom: 16,
        lineHeight: 34,
    },
    footer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    subText: {
        fontSize: 12,
        color: '#60A5FA',
        fontWeight: '600',
        fontStyle: 'italic',
    }
});
