import { StyleSheet } from 'react-native';

export const countryCardStyles = StyleSheet.create({
    countryCard: { borderRadius: 28, overflow: 'hidden', borderWidth: 1 },
    countryHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 20 },
    countryName: { fontSize: 17, fontWeight: '900' },
    countryCount: { fontSize: 11, fontWeight: '700', letterSpacing: 1, marginTop: 2 },
    accordionBody: { padding: 8 },
    regionTitle: {
        fontSize: 10,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 1,
        marginBottom: 12,
        marginLeft: 12,
        marginTop: 8,
    },
    itemRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: 16,
        borderRadius: 22,
        borderWidth: 1,
    },
    itemMainContent: { flexDirection: 'row', alignItems: 'center', gap: 12, flex: 1 },
    deleteAction: {
        backgroundColor: '#EF4444',
        justifyContent: 'center',
        alignItems: 'flex-end',
        width: 100,
        height: '100%',
        paddingRight: 20,
        borderRadius: 22,
        marginLeft: -20,
    },
    deleteBtnContent: { alignItems: 'center', justifyContent: 'center' },
    deleteText: { color: 'white', fontWeight: '600', fontSize: 12, marginTop: 4 },
    emojiBox: {
        width: 44,
        height: 44,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
    },
    itemName: { fontSize: 14, fontWeight: '700', lineHeight: 18 },
    itemDate: { fontSize: 10, fontWeight: '500', marginTop: 2 },
    statusIconBox: {
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
    },
});
