import { StyleSheet } from 'react-native';

import {
  tripStatsDashboardColors as colors,
  tripStatsDashboardRadii as radii,
  tripStatsDashboardShadows as shadows,
  tripStatsDashboardSpacing as spacing,
  tripStatsDashboardTypography as typography,
} from './tripStatsDashboardTokens';

export const tripStatsDashboardStyles = StyleSheet.create({
  screenBackground: {
    flex: 1,
    backgroundColor: colors.paper,
  },
  atmosphereLayer: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.18,
    backgroundColor: 'transparent',
  },
  grainLayer: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.16,
    backgroundColor: 'transparent',
  },
  scrollContent: {
    paddingHorizontal: spacing.xl,
    paddingTop: spacing.md,
    paddingBottom: spacing.xxxl,
    gap: spacing.lg,
  },
  railCard: {
    borderRadius: radii.lg,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    padding: spacing.md,
    gap: spacing.sm,
    boxShadow: shadows.card,
  },
  railHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  railCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  railMeta: {
    fontSize: typography.caption,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: colors.inkSoft,
  },
  railTitle: {
    fontSize: typography.section,
    lineHeight: 28,
    fontWeight: '700',
    color: colors.ink,
  },
  railSubtitle: {
    fontSize: typography.body,
    lineHeight: 20,
    color: colors.inkSoft,
  },
  heroCard: {
    borderRadius: radii.xl,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceStrong,
    padding: spacing.lg,
    gap: spacing.md,
    boxShadow: shadows.hero,
  },
  heroHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: spacing.md,
  },
  heroCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  heroEyebrow: {
    fontSize: typography.caption,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: colors.inkSoft,
  },
  heroTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: '800',
    letterSpacing: -0.6,
    color: colors.ink,
  },
  heroSubtitle: {
    fontSize: typography.body,
    lineHeight: 21,
    color: colors.inkSoft,
  },
  heroBadgeRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
  },
  heroBadge: {
    minHeight: 30,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.pill,
    borderCurve: 'continuous',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceMuted,
  },
  heroBadgeText: {
    fontSize: typography.caption,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: colors.inkSoft,
  },
  totalsCard: {
    borderRadius: radii.lg,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    padding: spacing.md,
    gap: spacing.md,
  },
  totalsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  totalsCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  totalsTitle: {
    fontSize: typography.section,
    lineHeight: 26,
    fontWeight: '700',
    color: colors.ink,
  },
  totalsSubtitle: {
    fontSize: typography.body,
    lineHeight: 20,
    color: colors.inkSoft,
  },
  totalsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  totalsTile: {
    flexGrow: 1,
    flexBasis: '47%',
    minHeight: 96,
    borderRadius: radii.md,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.pearlIvory,
    padding: spacing.md,
    gap: spacing.xs,
    boxShadow: shadows.card,
  },
  totalsValue: {
    fontSize: 26,
    lineHeight: 30,
    fontWeight: '800',
    color: colors.ink,
  },
  totalsLabel: {
    fontSize: typography.caption,
    lineHeight: 16,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: colors.inkSoft,
  },
  chapterCard: {
    borderRadius: radii.lg,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceMuted,
    padding: spacing.md,
    gap: spacing.sm,
  },
  chapterHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  chapterCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  chapterTitle: {
    fontSize: typography.section,
    lineHeight: 26,
    fontWeight: '700',
    color: colors.ink,
  },
  chapterSubtitle: {
    fontSize: typography.body,
    lineHeight: 20,
    color: colors.inkSoft,
  },
  chapterList: {
    gap: spacing.sm,
  },
  chapterItem: {
    borderRadius: radii.md,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceStrong,
    padding: spacing.md,
    gap: spacing.xs,
  },
  chapterItemTitle: {
    fontSize: typography.bodyStrong,
    lineHeight: 18,
    fontWeight: '700',
    color: colors.ink,
  },
  chapterItemMeta: {
    fontSize: typography.caption,
    lineHeight: 16,
    color: colors.inkSoft,
  },
  feedCard: {
    borderRadius: radii.lg,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surface,
    padding: spacing.md,
    gap: spacing.sm,
  },
  feedHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: spacing.sm,
  },
  feedCopy: {
    flex: 1,
    gap: spacing.xs,
  },
  feedTitle: {
    fontSize: typography.section,
    lineHeight: 26,
    fontWeight: '700',
    color: colors.ink,
  },
  feedSubtitle: {
    fontSize: typography.body,
    lineHeight: 20,
    color: colors.inkSoft,
  },
  feedList: {
    gap: spacing.sm,
  },
  feedItem: {
    borderRadius: radii.md,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.pearlMist,
    padding: spacing.md,
    gap: spacing.xs,
  },
  feedItemTitle: {
    fontSize: typography.bodyStrong,
    lineHeight: 18,
    fontWeight: '700',
    color: colors.ink,
  },
  feedItemMeta: {
    fontSize: typography.caption,
    lineHeight: 16,
    color: colors.inkSoft,
  },
  actionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
  },
  actionCard: {
    flexGrow: 1,
    flexBasis: '48%',
    borderRadius: radii.md,
    borderCurve: 'continuous',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceStrong,
    padding: spacing.md,
    gap: spacing.xs,
  },
  actionTitle: {
    fontSize: typography.bodyStrong,
    lineHeight: 18,
    fontWeight: '700',
    color: colors.ink,
  },
  actionDescription: {
    fontSize: typography.caption,
    lineHeight: 16,
    color: colors.inkSoft,
  },
  pill: {
    minHeight: 30,
    paddingHorizontal: spacing.sm,
    borderRadius: radii.pill,
    borderCurve: 'continuous',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.line,
    backgroundColor: colors.surfaceMuted,
  },
  pillText: {
    fontSize: typography.caption,
    lineHeight: 14,
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: colors.inkSoft,
  },
});

