import { StyleSheet } from 'react-native';

export const THEME_STYLES = StyleSheet.create({
    glass: {
        borderWidth: 1,
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.1,
        shadowRadius: 20,
        elevation: 10,
    },
});

export const tripStatsStyles = StyleSheet.create({
    container: {
        flex: 1,
    },
    backgroundContainer: {
        ...StyleSheet.absoluteFillObject,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 32,
    },
    headerTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#1E293B',
    },
    backButton: {
        width: 40,
        height: 40,
        borderRadius: 20,
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    mainCard: {
        borderRadius: 40,
        padding: 32,
        alignItems: 'center',
        marginBottom: 24,
        overflow: 'hidden',
    },
    shieldIconContainer: {
        padding: 16,
        backgroundColor: '#DCFCE7',
        borderRadius: 24,
        marginBottom: 16,
    },
    bigCount: {
        fontSize: 56,
        fontWeight: '900',
        color: '#1E293B',
        marginBottom: 8,
    },
    statDescription: {
        fontSize: 14,
        color: '#64748B',
        textAlign: 'center',
        lineHeight: 20,
        marginBottom: 24,
    },
    globalLink: {
        width: '100%',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingTop: 24,
        borderTopWidth: 1,
        borderTopColor: 'rgba(241, 245, 249, 0.6)',
    },
    globalLinkText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#94A3B8',
    },
    globalLinkRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    globalCountText: {
        fontSize: 14,
        fontWeight: '800',
        color: '#1E293B',
    },
    tripCard: {
        borderRadius: 32,
        padding: 24,
        marginBottom: 24,
        overflow: 'hidden',
    },
    tripHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
        marginBottom: 24,
    },
    mapIconBox: {
        width: 48,
        height: 48,
        borderRadius: 16,
        backgroundColor: '#F0F9FF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    tripTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#1E293B',
    },
    tripLocation: {
        fontSize: 12,
        color: '#64748B',
    },
    startButton: {
        width: '100%',
        height: 64,
        borderRadius: 24,
        backgroundColor: '#0F172A',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 12,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 5,
        marginBottom: 16,
    },
    startButtonDisabled: {
        backgroundColor: '#F1F5F9',
        shadowOpacity: 0,
    },
    startButtonText: {
        fontSize: 16,
        fontWeight: 'bold',
        color: 'white',
    },
    disclaimer: {
        fontSize: 11,
        color: '#94A3B8',
        textAlign: 'center',
        lineHeight: 16,
    },
    toastContainer: {
        position: 'absolute',
        top: 0,
        left: 20,
        right: 20,
        zIndex: 100,
        alignItems: 'center',
    },
    toastContent: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: 'rgba(15, 23, 42, 0.9)',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 30,
        gap: 12,
        overflow: 'hidden',
    },
    toastTitle: {
        color: 'white',
        fontWeight: '700',
        fontSize: 14,
    },
    toastMessage: {
        color: '#94A3B8',
        fontSize: 12,
    },
    activeIconCircleSmall: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#22C55E',
        alignItems: 'center',
        justifyContent: 'center',
    },
});
