import { ALLERGEN_TERMS, ALLERGY_TRANSLATIONS } from '@/services/staticTranslations';
import { AiTranslation } from './types';

export const isNullAiTranslation = (aiTranslation: AiTranslation, isAiLoaded: boolean) =>
  isAiLoaded && (aiTranslation === null || aiTranslation?.text === null);

export const translateAllergen = (allergen: string, targetCode: string) => {
  const lower = allergen.trim().toLowerCase();
  const titleCase = lower.charAt(0).toUpperCase() + lower.slice(1);
  const dict = ALLERGEN_TERMS[allergen] || ALLERGEN_TERMS[titleCase];
  return dict ? dict[targetCode] || allergen : allergen;
};

export const buildDisplayData = (countryCode: string | null | undefined, aiTranslation: AiTranslation) => {
  const code = countryCode || 'DEFAULT';
  const staticData = ALLERGY_TRANSLATIONS[code] || ALLERGY_TRANSLATIONS['DEFAULT'];
  const isAiLoaded = aiTranslation !== undefined;
  const hasAiContent = isAiLoaded && !!aiTranslation;

  if (hasAiContent) {
    return {
      language: aiTranslation.language,
      text: aiTranslation.text || staticData.text,
      sub: 'Auto-generated by AI Health Coach',
      isAiLoaded,
    };
  }

  return {
    language: staticData.language,
    text: staticData.text,
    sub: 'Traveler Safety Card (GPS Linked)',
    isAiLoaded,
  };
};

export const buildTravelerMessage = (
  baseText: string,
  aiTranslation: AiTranslation,
  countryCode: string | null | undefined,
  userAllergens: string[]
): string => {
  if (aiTranslation || userAllergens.length === 0) return baseText;
  const targetCode = countryCode || 'US';
  const translatedList = userAllergens.map((allergen) => translateAllergen(allergen, targetCode));
  return `${baseText}\n\n⚠️ My Allergies:\n${translatedList.join(', ')}`;
};
